# Generated by Django 4.0.10 on 2023-09-14 01:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('date_expiration', models.DateTimeField(default=datetime.datetime(2023, 9, 15, 1, 34, 6, 230380, tzinfo=utc))),
            ],
            bases=('authtoken.token',),
        ),
    ]
