# Generated by Django 4.0.10 on 2023-09-14 01:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 1, 34, 56, 290598, tzinfo=utc)),
        ),
    ]
